### ISSUE TITLE
No applicable SKUs exception

### ISSUE THREAD

**Issue by toofik2** [mmajcica/DevEnvBuild#19]
Installation of extensions fails. Tried on 3 machines running win10 and Visual studio 2019, as well as 2017 with no success. Trying to run as C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe also did not bring any other result. Below there is the content of log:

`03.08.2021 13:17:00 - Microsoft VSIX Installer
03.08.2021 13:17:00 - -------------------------------------------
03.08.2021 13:17:00 - vsixinstaller.exe version:
03.08.2021 13:17:00 - 16.11.9
03.08.2021 13:17:00 - -------------------------------------------
03.08.2021 13:17:00 - Command line parameters:
03.08.2021 13:17:00 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\<user>\Downloads\mmajcica.devenv-build-2.0.3.vsix
03.08.2021 13:17:00 - -------------------------------------------
03.08.2021 13:17:00 - Microsoft VSIX Installer
03.08.2021 13:17:00 - -------------------------------------------
03.08.2021 13:17:01 - Initializing Install...
03.08.2021 13:17:01 - Extension Details...
03.08.2021 13:17:01 - 	Identifier         : devenv-build
03.08.2021 13:17:01 - 	Name               : Build with devenv (Visual Studio)
03.08.2021 13:17:01 - 	Author             : mmajcica
03.08.2021 13:17:01 - 	Version            : 2.0.3
03.08.2021 13:17:01 - 	Description        : Build a project using devenv.com
03.08.2021 13:17:01 - 	Locale             : en-US
03.08.2021 13:17:01 - 	MoreInfoURL        : 
03.08.2021 13:17:01 - 	InstalledByMSI     : False
03.08.2021 13:17:01 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
03.08.2021 13:17:01 - 
03.08.2021 13:17:01 - 	SignatureState     : Unsigned
03.08.2021 13:17:01 - 	Supported Products : 
03.08.2021 13:17:01 - 		Microsoft.VisualStudio.Services
03.08.2021 13:17:01 - 			Version : 
03.08.2021 13:17:01 - 
03.08.2021 13:17:01 - 	References         : 
03.08.2021 13:17:01 - Signature Details...
03.08.2021 13:17:01 - 	Extension is not signed.
03.08.2021 13:17:01 - 
03.08.2021 13:17:01 - Searching for applicable products...
03.08.2021 13:17:01 - Found installed product - Global Location
03.08.2021 13:17:01 - Found installed product - Visual Studio Professional 2019
03.08.2021 13:17:01 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`

**Comment by mmajcica** [comment]
Not sure how this relates to this task, seems quite a bit out of scope.
