### ISSUE TITLE
Task in timeout, no Exit Code: 0 found

### ISSUE THREAD

**Issue by romualdginhoux** [mmajcica/DevEnvBuild#21]
Hi, we have an issue with a DevEnvBuild@2 step that goes to timeout repeatedly since a few days, while we haven't change anything in the repository and in the pipeline. Sometimes the step works.... 
The issue seems to be that sometimes the task does not return the expected Exit Code 0, so the pipeline goes to timeout.
I include below an extract of the pipeline and a copy of the logs for both a working build step and a timed out build step (both run on the same code!)

Any idea?

**Extract of pipeline**
    - task: DevEnvBuild@2
      displayName: Building setup solution (unencrypted installer)
      inputs:
        solution: '**\*SetupAzure.sln'
        buildCfg: '$(buildConfiguration)'
        buildPlatform: '$(buildPlatform)'
        vsVersion: '16.0'

**Extract of log for working build step**

2021-09-03T09:32:59.8088225Z ##[debug]Evaluating condition for step: 'Building setup solution (unencrypted installer)'
2021-09-03T09:32:59.8089915Z ##[debug]Evaluating: SucceededNode()
2021-09-03T09:32:59.8090362Z ##[debug]Evaluating SucceededNode:
2021-09-03T09:32:59.8091195Z ##[debug]=> True
2021-09-03T09:32:59.8091633Z ##[debug]Result: True
2021-09-03T09:32:59.8092201Z ##[section]Starting: Building setup solution (unencrypted installer)
2021-09-03T09:32:59.8202659Z ==============================================================================
2021-09-03T09:32:59.8202973Z Task         : DevEnv build (Visual Studio)
2021-09-03T09:32:59.8203296Z Description  : Build a project via the visual studio command-line invocation, devenv.cmd. Used for building eg. SSIS projects.
2021-09-03T09:32:59.8203577Z Version      : 2.0.5
2021-09-03T09:32:59.8203763Z Author       : Mario Majcica
2021-09-03T09:32:59.8204045Z Help         : Build your project via the visual studio command-line invocation, devenv.cmd
2021-09-03T09:32:59.8204353Z ==============================================================================
2021-09-03T09:33:02.0957771Z ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
2021-09-03T09:33:02.2285458Z ##[debug]Entering D:\a\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\2.0.5\task.ps1.
2021-09-03T09:33:02.2564882Z ##[debug]INPUT_SOLUTION: 'D:\a\1\s\**\*SetupAzure.sln'

[...]

2021-09-03T09:34:48.7360572Z Packaging file 'NLua.dll'...
2021-09-03T09:34:48.7593754Z Packaging file 'TMS.3.9.3604.0.t.zip'...
2021-09-03T09:34:48.7701502Z Packaging file 'vcinet4.dll'...
2021-09-03T09:34:48.8741909Z Packaging file 'TMS.3.3.3604.0.t.zip'...
2021-09-03T09:34:49.5218229Z Starting post-build events...
2021-09-03T09:34:49.6328973Z D:\a\1\s\StandAloneTMSController\StandAloneControllerSetup\..\Properties\Update.manifest
2021-09-03T09:34:49.6335034Z 1 File(s) copied
2021-09-03T09:34:49.6345705Z 
2021-09-03T09:34:49.6432657Z D:\a\1\s\StandAloneTMSController\StandAloneControllerSetup\..\..\RELEASENOTES.md
2021-09-03T09:34:49.6440460Z 1 File(s) copied
2021-09-03T09:34:49.6445733Z 
2021-09-03T09:34:49.6456593Z Post-build events finished
2021-09-03T09:34:49.6985687Z ========== Build: 8 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========
2021-09-03T09:34:51.5073750Z ##[debug]Exit code: 0
2021-09-03T09:34:51.5147165Z ##[debug]Leaving Invoke-VstsTool.
2021-09-03T09:34:51.5211496Z Build succeeded.
2021-09-03T09:34:51.5224930Z ##[debug]Leaving D:\a\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\2.0.5\task.ps1.
2021-09-03T09:34:51.5702845Z ##[section]Finishing: Building setup solution (unencrypted installer)

**Extract of log for failing (timeout) build step**

2021-09-03T10:01:53.3944625Z ##[debug]Evaluating condition for step: 'Building setup solution (unencrypted installer)'
2021-09-03T10:01:53.3946361Z ##[debug]Evaluating: SucceededNode()
2021-09-03T10:01:53.3946842Z ##[debug]Evaluating SucceededNode:
2021-09-03T10:01:53.3947756Z ##[debug]=> True
2021-09-03T10:01:53.3948261Z ##[debug]Result: True
2021-09-03T10:01:53.3949223Z ##[section]Starting: Building setup solution (unencrypted installer)
2021-09-03T10:01:53.4059504Z ==============================================================================
2021-09-03T10:01:53.4059856Z Task         : DevEnv build (Visual Studio)
2021-09-03T10:01:53.4060248Z Description  : Build a project via the visual studio command-line invocation, devenv.cmd. Used for building eg. SSIS projects.
2021-09-03T10:01:53.4060612Z Version      : 2.0.5
2021-09-03T10:01:53.4060820Z Author       : Mario Majcica
2021-09-03T10:01:53.4061145Z Help         : Build your project via the visual studio command-line invocation, devenv.cmd
2021-09-03T10:01:53.4061545Z ==============================================================================
2021-09-03T10:01:55.6362144Z ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
2021-09-03T10:01:55.7425229Z ##[debug]Entering D:\a\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\2.0.5\task.ps1.
2021-09-03T10:01:55.7727051Z ##[debug]INPUT_SOLUTION: 'D:\a\1\s\**\*SetupAzure.sln'

[...] 

2021-09-03T10:05:21.6263494Z Packaging file 'NLua.dll'...
2021-09-03T10:05:21.6414747Z Packaging file 'TMS.3.9.3604.0.t.zip'...
2021-09-03T10:05:21.6508284Z Packaging file 'vcinet4.dll'...
2021-09-03T10:05:21.7742129Z Packaging file 'TMS.3.3.3604.0.t.zip'...
2021-09-03T10:05:22.3418775Z Starting post-build events...
2021-09-03T10:05:22.9249078Z D:\a\1\s\StandAloneTMSController\StandAloneControllerSetup\..\Properties\Update.manifest
2021-09-03T10:05:22.9251303Z 1 File(s) copied
2021-09-03T10:05:22.9272574Z D:\a\1\s\StandAloneTMSController\StandAloneControllerSetup\..\..\RELEASENOTES.md
2021-09-03T10:05:22.9273738Z 1 File(s) copied
2021-09-03T10:05:22.9273999Z 
2021-09-03T10:05:22.9274377Z Post-build events finished
2021-09-03T10:05:22.9684663Z ========== Build: 8 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========
2021-09-03T10:59:41.9311836Z ##[debug]Re-evaluate condition on job cancellation for step: 'Building setup solution (unencrypted installer)'.
2021-09-03T10:59:42.0564850Z ##[debug]Leaving Invoke-VstsTool.
2021-09-03T10:59:42.0590577Z ##[debug]Leaving D:\a\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\2.0.5\task.ps1.
2021-09-03T10:59:42.2392029Z ##[error]The operation was canceled.
2021-09-03T10:59:42.2397470Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-09-03T10:59:42.2402065Z ##[section]Finishing: Building setup solution (unencrypted installer)

**Comment by xpouyat** [comment]
I have the same issue (with Visual Studio 2022).
I also opened a ticket [here](https://github.com/microsoft/azure-pipelines-tasks/issues/15697).
